modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="deathchest"
version="1.6.2c"
displayName="Death Chest"
displayURL="https://www.curseforge.com/minecraft/mc-mods/death-chest" #optional
updateJSONURL=""
credits="Smileycorp" #optional
authors="Smileycorp" #optional
description=""