modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="deathchest" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Death Chest" #mandatory
logoFile="deathchest.png" #optional
credits="" #optional
authors="Smileycorp" #optional
description='''

'''
